name: Verify Node Version Validation
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: HarithaVattikuti/setup-node@d452dbce2f5685ce3c9f161e7a34453129a1461c
        with:
          node-version: '24'

      - name: Check actual node version
        run: |
          node --version