name: Solution Workflow
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.1.x, 20.x, 21]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Set up Node.js ${{ matrix.node-version }} on ${{matrix.os}}
      uses: v-jitenderpalsingh/setup-node@node-validate-retry
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: |
        echo "Node.js version: $(node -v)"
        echo "NPM version: $(npm -v)"
