name: Solution Workflow
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
