name: Test retry logic for setup-node

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Print details
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"