name: Test Node nigtly build

on: [push, workflow_dispatch]

jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '27-nightly'
          package-manager-cache: false
      
      - run: node --version