name: Test workflow

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node
        uses: v-jitenderpalsingh/setup-node@test-retry
        with:
          node-version: '24'